[package]
name = "fractory-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]

[[bin]]
name = "dummy-daemon"
path = "tests/bin/dummy_daemon.rs"
required-features = ["tracing-subscriber", "integration-tests"]

[features]
default = []
integration-tests = ["dep:rand", "dep:parking_lot"]
service = ["dep:anyhow", "dep:flume", "dep:windows-service"]
tracing-subscriber = ["dep:tracing-subscriber"]

[dependencies]
anyhow = { workspace = true, optional = true }
bincode = { workspace = true, features = ["derive"] }
futures = { workspace = true }
parking_lot = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
tokio = { workspace = true, features = ["net"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true, features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
flume = { workspace = true, optional = true }
mio = { workspace = true }
ringbuf = { workspace = true }
widestring = { workspace = true }
windows-service = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_System_Threading",
]

[target.'cfg(unix)'.dependencies]
askama = { workspace = true }
nix = { workspace = true, features = ["fs", "user"] }
systemd = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
fractory-daemon = { workspace = true, features = ["integration-tests"] }
memchr = { workspace = true }
ntest = { workspace = true }
parking_lot = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "full"] }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
configparser = { workspace = true }
