name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-02-04-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Check
        run: cargo check --all-targets --locked --verbose

      - name: Build
        run: cargo build --locked --verbose

      - name: Test
        run: cargo test --locked --verbose
